version: '2.3'

services:
  flask:    # flask server for covid19 service web pages and APIs, with backend tensorflow servering
    build:
      context: ./covid19
    image: ai-service-flask:0.1.0
    hostname: flask
    restart: on-failure
    ports:
      - 8051-8053:5000 # tensorflow servring port
    volumes:
      - ./covid19:/app  # tf2 serving convention
